<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3xD0Ic\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3xD0Ic/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerD3xD0Ic.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerD3xD0Ic\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerD3xD0Ic\App_KernelProdContainer([
    'container.build_hash' => 'D3xD0Ic',
    'container.build_id' => 'c5f569e7',
    'container.build_time' => 1700231315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD3xD0Ic');
