<?php

namespace ContainerXDxeubV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateAdCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CreateAdCommand' shared autowired service.
     *
     * @return \App\Command\CreateAdCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CreateAdCommand.php';

        $container->privates['App\\Command\\CreateAdCommand'] = $instance = new \App\Command\CreateAdCommand(($container->privates['App\\Repository\\AdRepository'] ?? $container->load('getAdRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->services['App\\Controller\\AdsController'] ?? $container->load('getAdsControllerService')));

        $instance->setName('create ad');

        return $instance;
    }
}
